Fix host key verification error during git pull

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,10 +53,12 @@ jobs:
             if [ -d "fastapi-book-project" ]; then
               echo "Directory already exists. Pulling latest changes..."
               cd fastapi-book-project || { echo "Failed to navigate to project directory"; exit 1; }
-              git pull || { echo "Git pull failed"; exit 1; }
+
+              # Disable strict host key checking for git pull
+              GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git pull || { echo "Git pull failed"; exit 1; }
             else
               echo "Directory does not exist. Cloning repository..."
-              git clone https://github.com/danlewismuriuki/fastapi-book-project.git || { echo "Git clone failed"; exit 1; }
+              GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone https://github.com/danlewismuriuki/fastapi-book-project.git || { echo "Git clone failed"; exit 1; }
               cd fastapi-book-project || { echo "Failed to navigate to project directory"; exit 1; }
             fi
 
